AWSTemplateFormatVersion: 2010-09-09

Description: Creating a s3 bucket

Parameters:
  Bucketname:
    Type: String
    Description: "The prefix used for all S3 buckets."
    Default: ''

  RuleName:
    Type: String
    Description: "The rule name"
    Default: s3  
  
  Password:
    Type: String
    Description: Please enter a password 
    NoEcho: true

  VersioningConfiguration:
    Type: String
    Default: enabled
    AllowedValues:
     - "Enabled"
     - "Suspended"

  PasswordResetRequired:
    Type: String
    Description: Do you want to require users to create a new password on first login?
    ConstraintDescription: Must be a boolean value of true or false
    Default: true
    AllowedValues: 
    - "true"
    - "false"
   
  
Resources:
  Assets:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Bucketname
      VersioningConfiguration:
        Status: !Ref VersioningConfiguration
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE

  user:
    Type: AWS::IAM::User
    Properties:
      UserName: venu-dev
      LoginProfile:
        Password: !Ref Password
        PasswordResetRequired: !Ref PasswordResetRequired


  Group:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Dev
      ManagedPolicyArns:
       - arn:aws:iam::488617992296:policy/s3-policy

  Users:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'Group'
      Users: [!Ref 'user']

  CFNKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'user'

  Role:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub '${RuleName}-Role'
      Path: "/"     
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: 
              Service: 
                - "s3.amazonaws.com"
          Action: sts:AssumeRole  
       
  RolePolicies:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub '${RuleName}-policy'
      Roles:
        - Ref: "Role"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:       
        - Effect: Allow
          Action:
          - "s3:GetBucketLocation"
          - "s3:ListAllMyBuckets"       
          Resource: arn:aws:s3:::*
        - Effect: Allow 
          Action:
          - "s3:*"
          Resource:
              - !sub  ["arn:aws:s3:::", Ref: "Bucketname"]
              - !sub  ["arn:aws:s3:::", Ref: "Bucketname/*"]     
Outputs:
  AccessKey:
    Value: !Ref 'CFNKeys'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [CFNKeys, SecretAccessKey]
    Description: AWSSecretAccessKey of new user     
  
  UserARN:
    Description: The ARN associated with the IAM User account
    Value: !GetAtt user.Arn

  UserName: 
    Description: The UserName associated with the IAM User account
    Value: !Ref user

  RoleARN:
    Description: The ARN associated with the IAM User account
    Value: !GetAtt Role.Arn